# Document:
# http://simiki.org/docs/configuration.html

url: 9avalon/wiki
title: Miguel's Wiki
keywords: 
description: Miguel个人wiki
author: Miguel

root: /wiki/

deploy:
  - type: git
    remote: origin
    branch: gh-pages

